Improved readme and function extension specification syntax improvements
a-sit-plus/jsonpath pull request #9
Opened 2024-05-07 20:11 UTC by acrusage

Improved readme along with some breaking changes to improve definition and testing of function extensions.

2024-05-07 20:12 UTC, acrusage commented
I'm unsure about the following though:
Global variables for the function extension definition have been created in the process. 
They were singletons before, but this is no longer possible as the functions are now instances. 
Are global variables fine like this, or what would be better practice?

2024-05-08 15:54 UTC, JesusMcCloud commented
> I'm unsure about the following though: Global variables for the function extension definition have been created in the process. They were singletons before, but this is no longer possible as the functions are now instances. Are global variables fine like this, or what would be better practice?

You mean as part of the object, or did I overlook something?

2024-05-08 15:58 UTC, JesusMcCloud requested changes
Readme looks good!

One minor thing:
Use the functional Napier interface (e.g `Napier.e{}` (curly braces!)), as it completely omits all logging invocations for disabled log levels.

2024-05-13 13:37 UTC, acrusage-iaik commented on jsonpath/src/commonMain/kotlin/at/asitplus/jsonpath/core/functionExtensions/countFunctionExtension.kt
> +internal val countFunctionExtension by lazy {
@JesusMcCloud Regarding https://github.com/a-sit-plus/jsonpath/pull/9#issuecomment-2100896623
Is there a better way to define this extension without making it a global variable?

2024-05-13 13:51 UTC, acrusage-iaik commented
Fixed in commit a918d6b1d0574ae9c69bfecbc167b72632b0ed4d

2024-05-13 13:51 UTC, acrusage-iaik commented
> Readme looks good!
> 
> One minor thing: Use the functional Napier interface (e.g `Napier.e{}` (curly braces!)), as it completely omits all logging invocations for disabled log levels.

Fixed in commit a918d6b1d0574ae9c69bfecbc167b72632b0ed4d

2024-05-13 14:39 UTC, JesusMcCloud approved these changes

2024-05-13 14:42 UTC, merged